# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "uv"
    directory: "backend/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "ruff"
      - dependency-name: "mypy"
      - dependency-name: "pre-commit"
      - dependency-name: "pytest"
      - dependency-name: "fastapi"
      - dependency-name: "sqlmodel"
      - dependency-name: "uvicorn"
      - dependency-name: "boto3"
      - dependency-name: "alembic"
      - dependency-name: "sentry-sdk"
      - dependency-name: "logfire"
  - package-ecosystem: "docker"
    directory: "backend/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "python"
      - dependency-name: "ghcr.io/astral-sh/uv"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "postgres"
      - dependency-name: "localstack/localstack"
      - dependency-name: "traefik"
