name: fastemplate

services:
  migrate:
    image: ghcr.io/frgfm/fastemplate:latest
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - RESEND_VERIFY_API_KEY=false
    command: ["sh", "-c", "alembic upgrade head"]

  backend:
    image: ghcr.io/frgfm/fastemplate:latest
    build:
      context: ./backend
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - RESEND_VERIFY_API_KEY=false
      - DEBUG=false
    volumes:
      - ./backend/app/:/app/app/
